# 1. Intorduction

Before we can start preprocessing the data, we first need to analyize it, in order to understand the data. This notebook will be used, to perform basic analysis over the two data sets, including the loan dataset as well as the breast cancer dataset.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# 2. Loan Dataset Analysis

In [5]:
ds_loan = pd.read_csv('./data/ds_loan/loan-10k.lrn.csv')

In [6]:
display(ds_loan.head())

,ID,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,emp_length,home_ownership,annual_inc,...,debt_settlement_flag,issue_d_month,issue_d_year,earliest_cr_line_month,earliest_cr_line_year,last_pymnt_d_month,last_pymnt_d_year,last_credit_pull_d_month,last_credit_pull_d_year,grade
0,24341,12500.0,12500.0,12500.0,36 months,7.21,387.17,< 1 year,MORTGAGE,81000.0,...,N,6,2018,6,2000,2,2019,2,2019,A
1,67534,33850.0,33850.0,33775.0,60 months,20.99,915.57,1 year,MORTGAGE,80000.0,...,N,10,2015,9,1984,2,2019,2,2019,E
2,35080,10000.0,10000.0,10000.0,60 months,20.00,264.94,< 1 year,RENT,36580.0,...,N,9,2017,10,2006,1,2018,11,2018,D
3,4828,20250.0,20250.0,20250.0,36 months,14.31,695.15,9 years,RENT,48700.0,...,N,0,2015,6,1996,6,2016,9,2017,C
4,59259,25000.0,25000.0,25000.0,36 months,14.99,866.52,1 year,MORTGAGE,85000.0,...,N,11,2016,0,2002,2,2019,2,2019,C

In [7]:
ds_loan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 92 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          10000 non-null  int64
 1   loan_amnt                   10000 non-null  float64
 2   funded_amnt                 10000 non-null  float64
 3   funded_amnt_inv             10000 non-null  float64
 4   term                        10000 non-null  object
 5   int_rate                    10000 non-null  float64
 6   installment                 10000 non-null  float64
 7   emp_length                  10000 non-null  object
 8   home_ownership              10000 non-null  object
 9   annual_inc                  10000 non-null  float64
 10  verification_status         10000 non-null  object
 11  loan_status                 10000 non-null  object
 12  pymnt_plan                  10000 non-null  object
 13  purpose                     10000 non-null  object
 14  addr_state                  10000 non-null  object
 15  dti                         10000 non-null  float64
 16  delinq_2yrs                 10000 non-null  float64
 17  fico_range_low              10000 non-null  float64
 18  fico_range_high             10000 non-null  float64
 19  inq_last_6mths              10000 non-null  float64
 20  open_acc                    10000 non-null  float64
 21  pub_rec                     10000 non-null  float64
 22  revol_bal                   10000 non-null  float64
 23  revol_util                  10000 non-null  float64
 24  total_acc                   10000 non-null  float64
 25  initial_list_status         10000 non-null  object
 26  out_prncp                   10000 non-null  float64
 27  out_prncp_inv               10000 non-null  float64
 28  total_pymnt                 10000 non-null  float64
 29  total_pymnt_inv             10000 non-null  float64
 30  total_rec_prncp             10000 non-null  float64
 31  total_rec_int               10000 non-null  float64
 32  total_rec_late_fee          10000 non-null  float64
 33  recoveries                  10000 non-null  float64
 34  collection_recovery_fee     10000 non-null  float64
 35  last_pymnt_amnt             10000 non-null  float64
 36  last_fico_range_high        10000 non-null  float64
 37  last_fico_range_low         10000 non-null  float64
 38  collections_12_mths_ex_med  10000 non-null  float64
 39  policy_code                 10000 non-null  float64
 40  application_type            10000 non-null  object
 41  acc_now_delinq              10000 non-null  float64
 42  tot_coll_amt                10000 non-null  float64
 43  tot_cur_bal                 10000 non-null  float64
 44  total_rev_hi_lim            10000 non-null  float64
 45  acc_open_past_24mths        10000 non-null  float64
 46  avg_cur_bal                 10000 non-null  float64
 47  bc_open_to_buy              10000 non-null  float64
 48  bc_util                     10000 non-null  float64
 49  chargeoff_within_12_mths    10000 non-null  float64
 50  delinq_amnt                 10000 non-null  float64
 51  mo_sin_old_il_acct          10000 non-null  float64
 52  mo_sin_old_rev_tl_op        10000 non-null  float64
 53  mo_sin_rcnt_rev_tl_op       10000 non-null  float64
 54  mo_sin_rcnt_tl              10000 non-null  float64
 55  mort_acc                    10000 non-null  float64
 56  mths_since_recent_bc        10000 non-null  float64
 57  mths_since_recent_inq       10000 non-null  float64
 58  num_accts_ever_120_pd       10000 non-null  float64
 59  num_actv_bc_tl              10000 non-null  float64
 60  num_actv_rev_tl             10000 non-null  float64
 61  num_bc_sats                 10000 non-null  float64
 62  num_bc_tl                   10000 non-null  float64
 63  num_il_tl                   10000 non-null  float64
 64  num_op_rev_tl               10000 non-null  float64
 65  num_rev_accts               10000 non-null  float64
 66  num_rev_tl_bal_gt_0         10000 non-null  float64
 67  num_sats                    10000 non-null  float64
 68  num_tl_120dpd_2m            10000 non-null  float64
 69  num_tl_30dpd                10000 non-null  float64
 70  num_tl_90g_dpd_24m          10000 non-null  float64
 71  num_tl_op_past_12m          10000 non-null  float64
 72  pct_tl_nvr_dlq              10000 non-null  float64
 73  percent_bc_gt_75            10000 non-null  float64
 74  pub_rec_bankruptcies        10000 non-null  float64
 75  tax_liens                   10000 non-null  float64
 76  tot_hi_cred_lim             10000 non-null  float64
 77  total_bal_ex_mort           10000 non-null  float64
 78  total_bc_limit              10000 non-null  float64
 79  total_il_high_credit_limit  10000 non-null  float64
 80  hardship_flag               10000 non-null  object
 81  disbursement_method         10000 non-null  object
 82  debt_settlement_flag        10000 non-null  object
 83  issue_d_month               10000 non-null  int64
 84  issue_d_year                10000 non-null  int64
 85  earliest_cr_line_month      10000 non-null  int64
 86  earliest_cr_line_year       10000 non-null  int64
 87  last_pymnt_d_month          10000 non-null  int64
 88  last_pymnt_d_year           10000 non-null  int64
 89  last_credit_pull_d_month    10000 non-null  int64
 90  last_credit_pull_d_year     10000 non-null  int64
 91  grade                       10000 non-null  object
dtypes: float64(69), int64(9), object(14)
memory usage: 7.0+ MB

In [9]:
ds_loan.shape

(10000, 92)

In [11]:
ds_loan.describe()

,ID,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,fico_range_low,...,total_bc_limit,total_il_high_credit_limit,issue_d_month,issue_d_year,earliest_cr_line_month,earliest_cr_line_year,last_pymnt_d_month,last_pymnt_d_year,last_credit_pull_d_month,last_credit_pull_d_year
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,1.000000e+04,10000.000000,10000.000000,10000.000000,...,1.000000e+04,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,50043.430200,15631.152500,15631.152500,15625.992500,13.216959,461.084183,8.212897e+04,19.089188,0.303400,698.179500,...,2.423097e+04,48294.371800,5.77670,2016.003100,5.724600,2000.017900,4.003000,2017.747300,3.334200,2018.453400
std,28982.440166,9314.246117,9314.246117,9312.426843,4.855838,269.903751,6.769284e+04,9.523219,0.841201,32.170977,...,2.539548e+04,46981.179499,3.40482,1.587496,3.382558,7.302583,3.224257,1.463235,2.909666,0.963494
min,0.000000,1000.000000,1000.000000,1000.000000,5.310000,30.120000,5.000000e+03,0.000000,0.000000,660.000000,...,2.000000e+02,0.000000,0.00000,2012.000000,0.000000,1965.000000,0.000000,2012.000000,0.000000,2012.000000
25%,24873.250000,8350.000000,8350.000000,8343.750000,9.750000,263.770000,5.000000e+04,12.437500,0.000000,675.000000,...,8.800000e+03,18881.250000,3.00000,2015.000000,3.000000,1996.000000,2.000000,2017.000000,2.000000,2018.000000
50%,50033.500000,14000.000000,14000.000000,14000.000000,12.730000,396.780000,7.000000e+04,18.330000,0.000000,690.000000,...,1.710000e+04,36533.500000,6.00000,2016.000000,6.000000,2001.000000,2.000000,2018.000000,2.000000,2019.000000
75%,75261.500000,21000.000000,21000.000000,21000.000000,16.010000,616.337500,9.700000e+04,24.930000,0.000000,715.000000,...,3.140000e+04,63500.500000,9.00000,2017.000000,9.000000,2005.000000,6.000000,2019.000000,3.000000,2019.000000
max,99999.000000,40000.000000,40000.000000,40000.000000,30.990000,1717.630000,3.200000e+06,168.520000,16.000000,845.000000,...,1.090700e+06,768775.000000,11.00000,2018.000000,11.000000,2015.000000,11.000000,2019.000000,11.000000,2019.000000